# DO NOT CHANGE IT
Version: V4

# ROS related paramaters
TopicQueue: 10

# Robot-Connection related parameters
RobotPort: 9559
RobotIP: 198.18.0.1
DriverBrokerPort: 54000
DriverBrokerIP: 0.0.0.0

# Communication related parameters
HighCommunicationFrequency: 15
LowCommunicationFrequency: 10
# 100Hz are perfect for Webots, 5-10Hz works really beautiful on my real Nao
ControllerFrequency: 10

# Robot related parameters
JointPrecision: 0.00174532925
OdomFrame: odom
